//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.225
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DomainCommonSE.ConfigLibrary.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ObjectExplorerControlLocalization {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ObjectExplorerControlLocalization() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DomainCommonSE.ConfigLibrary.Localization.ObjectExplorerControlLocalization", typeof(ObjectExplorerControlLocalization).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DB.
        /// </summary>
        internal static string DbNodeTitle {
            get {
                return ResourceManager.GetString("DbNodeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete type &apos;{0}&apos; is not supported.
        /// </summary>
        internal static string DeleteTypeNotSupportedError {
            get {
                return ResourceManager.GetString("DeleteTypeNotSupportedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit type &apos;{0}&apos; is not supported.
        /// </summary>
        internal static string EditTypeNotSupportedError {
            get {
                return ResourceManager.GetString("EditTypeNotSupportedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Link collection node is not found.
        /// </summary>
        internal static string LinkCollectionNodeNotFoundError {
            get {
                return ResourceManager.GetString("LinkCollectionNodeNotFoundError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Links.
        /// </summary>
        internal static string LinksNodeTitle {
            get {
                return ResourceManager.GetString("LinksNodeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Object queries node is not found.
        /// </summary>
        internal static string ObjectQueriesNodeNotFoundError {
            get {
                return ResourceManager.GetString("ObjectQueriesNodeNotFoundError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Object queries.
        /// </summary>
        internal static string ObjectQueryCollectionNodeTitle {
            get {
                return ResourceManager.GetString("ObjectQueryCollectionNodeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Objects.
        /// </summary>
        internal static string ObjectsNodeTitle {
            get {
                return ResourceManager.GetString("ObjectsNodeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Objects root node is not found.
        /// </summary>
        internal static string ObjectsRootNodeNotFoundError {
            get {
                return ResourceManager.GetString("ObjectsRootNodeNotFoundError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Properties.
        /// </summary>
        internal static string PropertiesNodeTitle {
            get {
                return ResourceManager.GetString("PropertiesNodeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property collection node is not found.
        /// </summary>
        internal static string PropertyCollectionNodeNotFoundError {
            get {
                return ResourceManager.GetString("PropertyCollectionNodeNotFoundError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Root DB node is not found.
        /// </summary>
        internal static string RootDbNodeNotFoundError {
            get {
                return ResourceManager.GetString("RootDbNodeNotFoundError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save changes?.
        /// </summary>
        internal static string SaveChangesQuestion {
            get {
                return ResourceManager.GetString("SaveChangesQuestion", resourceCulture);
            }
        }
    }
}
