//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.225
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DomainCommonSE.ConfigLibrary.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class UILocalization {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal UILocalization() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DomainCommonSE.ConfigLibrary.Localization.UILocalization", typeof(UILocalization).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete object.
        /// </summary>
        internal static string DeleteEntityObjectCaption {
            get {
                return ResourceManager.GetString("DeleteEntityObjectCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete link.
        /// </summary>
        internal static string DeleteEntityObjectLinkCaption {
            get {
                return ResourceManager.GetString("DeleteEntityObjectLinkCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you really want to delete link with code &apos;{0}&apos;?.
        /// </summary>
        internal static string DeleteEntityObjectLinkQuestion {
            get {
                return ResourceManager.GetString("DeleteEntityObjectLinkQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete property.
        /// </summary>
        internal static string DeleteEntityObjectPropertyCaption {
            get {
                return ResourceManager.GetString("DeleteEntityObjectPropertyCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you really want to delete property with code &apos;{0}&apos;?.
        /// </summary>
        internal static string DeleteEntityObjectPropertyQuestion {
            get {
                return ResourceManager.GetString("DeleteEntityObjectPropertyQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you really want to delete object with code &apos;{0}&apos;?.
        /// </summary>
        internal static string DeleteEntityObjectQuestion {
            get {
                return ResourceManager.GetString("DeleteEntityObjectQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete object query.
        /// </summary>
        internal static string DeleteObjectQueryCaption {
            get {
                return ResourceManager.GetString("DeleteObjectQueryCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you really want to delete object query with code &apos;{0}&apos;?.
        /// </summary>
        internal static string DeleteObjectQueryQuestion {
            get {
                return ResourceManager.GetString("DeleteObjectQueryQuestion", resourceCulture);
            }
        }
    }
}
